name: PR Checks

on:
  pull_request:
    branches: [main, master]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Check build
        run: npm run build

  database-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Start Supabase
        run: npx supabase start

      - name: Check database migrations
        run: npx supabase db diff --schema public --use-migra

      - name: Test seed script
        run: SEED_DAYS=7 npm run seed

      - name: Stop Supabase
        run: npx supabase stop